base_url = 'http://localhost:5000/api/v1'
loginAPI = '/auth/login'
addCompanyAPI = '/company/company'
addBranchAPI='/company/branch'
getCompanyAPI = '/company/company'
getBranchesAPI = '/company/branches'
getCompanyTrainersAPI = '/company/trainers'
getCompanyFieldsAPI = '/company/fields'
submitRequestAPI='/request/request'
deleteRequestAPI = '/request/request/'
getPendingRequestAPI = '/request/pendingRequests'
universityUsername = 'ptuk.en'
companyUsername= 'asal.ra'
password = '123'

